  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '支付记录表',
  `orderId` varchar(50) NOT NULL DEFAULT '' COMMENT '订单流水号',
  `uid` varchar(32) NOT NULL DEFAULT '' COMMENT '用户id',
  `companyId` int(11) NOT NULL DEFAULT '0' COMMENT '服务商id',
  `pingId` varchar(40) NOT NULL DEFAULT '' COMMENT 'ping++交易流水号',
  `channel` varchar(30) NOT NULL DEFAULT '' COMMENT '支付渠道',
  `transaction_no` varchar(100) NOT NULL DEFAULT '' COMMENT '渠道交易流水号',
  `systemCode` tinyint(3) NOT NULL DEFAULT '0' COMMENT '平台编号 1空间平台 2投资平台 3培训平台 4市场平台 5导师平台 6数据平台 7服务平台 8创新平台',
  `platOrderId` varchar(50) NOT NULL DEFAULT '' COMMENT '平台订单号',
  `card_type` tinyint(1) NOT NULL COMMENT '使用优惠券类型 0不使用 1平台优惠券',
  `amount` int(11) NOT NULL DEFAULT '0' COMMENT '支付金额：分',
  `card_amount` int(11) NOT NULL COMMENT '优惠券金额：分',
  `express_fee` int(11) NOT NULL COMMENT '快递费：分',
  `pay_amount` int(11) NOT NULL DEFAULT '0' COMMENT '实付金额：分',
  `pay_at` datetime DEFAULT NULL COMMENT '支付时间',
  `confirmTime` datetime DEFAULT NULL COMMENT '用户确认时间',
  `fee` int(11) NOT NULL DEFAULT '0' COMMENT '渠道手续费：分',
  `fee_rate` varchar(5) NOT NULL DEFAULT '' COMMENT '渠道手续费率',
  `deposit_amount` int(11) NOT NULL DEFAULT '0' COMMENT '应缴纳的保证金：分',
  `deposit_rate` int(10) NOT NULL DEFAULT '0' COMMENT '保证金缴纳比例',
  `divide_amount` int(11) NOT NULL DEFAULT '0' COMMENT '国安分成金额：分',
  `divide_rate` int(10) NOT NULL DEFAULT '0' COMMENT '国安分成比例',
  `refundId` int(11) NOT NULL DEFAULT '0' COMMENT '退款id',
  `billId` int(11) NOT NULL DEFAULT '0' COMMENT '账单id',
  `clear_amount` int(11) NOT NULL DEFAULT '0' COMMENT '客户结算金额：分',
  `clear_at` datetime DEFAULT NULL COMMENT '结算时间',
  `is_check` tinyint(1) NOT NULL DEFAULT '0' COMMENT '渠道是否已对账 0否 1是',
  `check_at` datetime DEFAULT NULL COMMENT '对账时间',
  `bug_type` int(11) NOT NULL DEFAULT '0' COMMENT '异常类型',
  `bug_status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '异常状态 0待检查 1有异常 2无异常 3已处理',
  `client_ip` varchar(20) NOT NULL DEFAULT '' COMMENT '支付用户ip地址',
  `status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '订单状态:0未支付 1已支付 2已确认 3已结算 4 退款中 5已退款 6已结算退款',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间',
  `create_at` datetime DEFAULT NULL COMMENT '创建时间',
  `info` text COMMENT '调试信息',
  `phone` varchar(255) DEFAULT '' COMMENT '手机号',
  `act_id` int(11) DEFAULT NULL COMMENT '活动id',
  `title` varchar(255) DEFAULT '' COMMENT '活动标题',